"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MideaDeviceType = void 0;
var MideaDeviceType;
(function (MideaDeviceType) {
    MideaDeviceType[MideaDeviceType["Plug"] = 16] = "Plug";
    MideaDeviceType[MideaDeviceType["RemoteController"] = 17] = "RemoteController";
    MideaDeviceType[MideaDeviceType["AirBox"] = 18] = "AirBox";
    MideaDeviceType[MideaDeviceType["Light"] = 19] = "Light";
    MideaDeviceType[MideaDeviceType["Curtain"] = 20] = "Curtain";
    MideaDeviceType[MideaDeviceType["MBox"] = 27] = "MBox";
    MideaDeviceType[MideaDeviceType["Dehumidifier"] = 161] = "Dehumidifier";
    MideaDeviceType[MideaDeviceType["AirConditioner"] = 172] = "AirConditioner";
    MideaDeviceType[MideaDeviceType["MicroWaveOven"] = 176] = "MicroWaveOven";
    MideaDeviceType[MideaDeviceType["BigOven"] = 177] = "BigOven";
    MideaDeviceType[MideaDeviceType["SteamerOven"] = 178] = "SteamerOven";
    MideaDeviceType[MideaDeviceType["Sterilizer"] = 179] = "Sterilizer";
    MideaDeviceType[MideaDeviceType["Toaster"] = 180] = "Toaster";
    MideaDeviceType[MideaDeviceType["Hood"] = 182] = "Hood";
    MideaDeviceType[MideaDeviceType["Hob"] = 183] = "Hob";
    MideaDeviceType[MideaDeviceType["VacuumCleaner"] = 184] = "VacuumCleaner";
    MideaDeviceType[MideaDeviceType["Induction"] = 185] = "Induction";
    MideaDeviceType[MideaDeviceType["Refrigerator"] = 202] = "Refrigerator";
    MideaDeviceType[MideaDeviceType["MDV"] = 204] = "MDV";
    MideaDeviceType[MideaDeviceType["AirWaterHeater"] = 205] = "AirWaterHeater";
    MideaDeviceType[MideaDeviceType["PulsatorWasher"] = 218] = "PulsatorWasher";
    MideaDeviceType[MideaDeviceType["DurmWasher"] = 219] = "DurmWasher";
    MideaDeviceType[MideaDeviceType["ClothesDryer"] = 220] = "ClothesDryer";
    MideaDeviceType[MideaDeviceType["DishWasher"] = 225] = "DishWasher";
    MideaDeviceType[MideaDeviceType["ElectricWaterHeater"] = 226] = "ElectricWaterHeater";
    MideaDeviceType[MideaDeviceType["GasWaterHeater"] = 227] = "GasWaterHeater";
    MideaDeviceType[MideaDeviceType["RiceCooker"] = 234] = "RiceCooker";
    MideaDeviceType[MideaDeviceType["InductionCooker"] = 235] = "InductionCooker";
    MideaDeviceType[MideaDeviceType["PressureCooker"] = 236] = "PressureCooker";
    MideaDeviceType[MideaDeviceType["WaterPurifier"] = 237] = "WaterPurifier";
    MideaDeviceType[MideaDeviceType["SoybeanMachine"] = 239] = "SoybeanMachine";
    MideaDeviceType[MideaDeviceType["ElectricFanner"] = 250] = "ElectricFanner";
    MideaDeviceType[MideaDeviceType["ElectricHeater"] = 251] = "ElectricHeater";
    MideaDeviceType[MideaDeviceType["AirPurifier"] = 252] = "AirPurifier";
    MideaDeviceType[MideaDeviceType["Humidifier"] = 253] = "Humidifier";
    MideaDeviceType[MideaDeviceType["AirConditionFanner"] = 254] = "AirConditionFanner";
    MideaDeviceType[MideaDeviceType["AllType"] = 255] = "AllType";
})(MideaDeviceType = exports.MideaDeviceType || (exports.MideaDeviceType = {}));
